
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { 'ruby_rails_reminders_development' } %> 
  username: <%= ENV.fetch("POSTGRES_USER") { 'ruby_rails_reminders' } %> 
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'ruby_rails_reminders' } %> 
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %> 

test:
  <<: *default
  database: ruby_rails_reminders_test

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %> 
  username: <%= ENV["POSTGRES_USER"] %> 
  password: <%= ENV["POSTGRES_PASSWORD"] %> 
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
