
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %> 
  username: <%= ENV["POSTGRES_USER"] %> 
  password: <%= ENV["POSTGRES_PASSWORD"] %> 
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>

test:
  <<: *development
  database: ruby_rails_reminders_test

production:
  <<: *default
  database: ruby_rails_reminders_production
